//extra class 22 feb 2021
public class questions4 {
    public static class TreeNode{
        int val = 0;
        TreeNode left = null;
        TreeNode right = null;

        TreeNode(int val){
            this.val = val;
        }
    }

    //968 ===============================================================================
    /*  -1 : cam reqd
         0 : i am camera
         1 : i'm covered
    */
    int cam = 0;
    public int calCamera(TreeNode node){
        if(node == null)
            return 1;
        
        int la = calCamera(node.left);
        int ra = calCamera(node.right);
        
        if(la == -1 || ra == -1){
            cam++;
            return 0;
        }
        if(la == 0 || ra == 0)
            return 1;
        
        return -1;
    }
    public int minCameraCover(TreeNode root) {        
        int ans = calCamera(root);
        if(ans == -1)
            cam++;
        return cam;
    }

    //337 =======================================================================================
    //arr[0] = max amount generated by not robbing this node
    //arr[1] = max amount generated by robbing this node
    
    int[] helper(TreeNode node){
        if(node == null){
            int[] base = new int[2];
            base[0] = 0; base[1] = 0;
            return base;
        }
        if(node.left == null && node.right == null){
            int[] base = new int[2];
            base[0] = 0; base[1] = node.val;
            return base;
        }
        
        int[] lAns = helper(node.left);
        int[] rAns = helper(node.right);
        
        int[] myAns = new int[2];
        myAns[0] = Math.max(lAns[0], lAns[1]) + Math.max(rAns[0], rAns[1]);
        myAns[1] = node.val + lAns[0] + rAns[0];
        
        return myAns;
    }
    public int rob(TreeNode root) {
        int[] ans = helper(root);
        return Math.max(ans[0], ans[1]);
    }

    

    public static void main(String[] args){

    }
}
